#include <amxmodx>

// v35: cvar_compat -- the phone gamedll does not register some cvars that
// popular mods take for granted, and many mod addons call get_cvar_pointer()
// in plugin_init() for cvars that the main mod registers LATER (plugins.ini
// order). A zero pointer there makes every later get_pcvar_num() abort with
// "Invalid CVAR pointer (handle 0) used in native get_pcvar_num".
// This plugin pre-registers those cvars at the very top of plugins.ini so
// every lookup succeeds no matter what order the user installs things in:
//   - bot_quota           : CZ-bot cvar, NOT registered by the ported gamedll
//   - amx_show_activity   : normally owned by admin.amxx (order-dependent)
//   - the full ZP 4.3 zp_* set (defaults identical to zombie_plague40.sma).
// Mods that register the same cvar later simply reuse the existing one and
// get a valid handle back (AMXX CvarManager re-uses engine-existing cvars).

public plugin_init()
{
	register_plugin("CVAR Compat", "1.0", "cs16-amxx-android")

	// platform-missing cvars
	register_cvar("bot_quota", "0")
	register_cvar("amx_show_activity", "2")

	// Zombie Plague 4.3 full cvar surface (canonical defaults)
	register_cvar("zp_admin_knife_models_human", "0")
	register_cvar("zp_admin_knife_models_zombie", "0")
	register_cvar("zp_admin_models_human", "1")
	register_cvar("zp_admin_models_zombie", "1")
	register_cvar("zp_block_suicide", "1")
	register_cvar("zp_blockuse_pushables", "1")
	register_cvar("zp_buy_custom", "1")
	register_cvar("zp_buyzone_time", "0.0")
	register_cvar("zp_deathmatch", "0")
	register_cvar("zp_delay", "10")
	register_cvar("zp_extra_antidote", "1")
	register_cvar("zp_extra_antidote_limit", "999")
	register_cvar("zp_extra_infbomb", "1")
	register_cvar("zp_extra_infbomb_limit", "999")
	register_cvar("zp_extra_items", "1")
	register_cvar("zp_extra_madness", "1")
	register_cvar("zp_extra_madness_duration", "5.0")
	register_cvar("zp_extra_madness_limit", "999")
	register_cvar("zp_extra_nvision", "1")
	register_cvar("zp_extra_weapons", "1")
	register_cvar("zp_fire_damage", "5")
	register_cvar("zp_fire_duration", "10")
	register_cvar("zp_fire_grenades", "1")
	register_cvar("zp_fire_slowdown", "0.5")
	register_cvar("zp_flare_color", "0")
	register_cvar("zp_flare_duration", "60")
	register_cvar("zp_flare_size", "25")
	register_cvar("zp_flash_charge", "5")
	register_cvar("zp_flash_custom", "0")
	register_cvar("zp_flash_distance", "1000")
	register_cvar("zp_flash_drain", "1")
	register_cvar("zp_flash_show_all", "1")
	register_cvar("zp_flash_size", "10")
	register_cvar("zp_frost_duration", "3")
	register_cvar("zp_frost_grenades", "1")
	register_cvar("zp_hud_display", "1")
	register_cvar("zp_hud_icons", "1")
	register_cvar("zp_human_armor_protect", "1")
	register_cvar("zp_human_damage_reward", "500")
	register_cvar("zp_human_frags_for_kill", "1")
	register_cvar("zp_human_gravity", "1.0")
	register_cvar("zp_human_health", "100")
	register_cvar("zp_human_last_extrahp", "0")
	register_cvar("zp_human_speed", "240")
	register_cvar("zp_human_unlimited_ammo", "0")
	register_cvar("zp_infection_allow_respawn", "1")
	register_cvar("zp_infection_particles", "1")
	register_cvar("zp_infection_screenfade", "1")
	register_cvar("zp_infection_screenshake", "1")
	register_cvar("zp_infection_sparkle", "1")
	register_cvar("zp_infection_tracers", "1")
	register_cvar("zp_keep_health_on_disconnect", "1")
	register_cvar("zp_knockback", "0")
	register_cvar("zp_knockback_damage", "1")
	register_cvar("zp_knockback_distance", "500")
	register_cvar("zp_knockback_ducking", "0.25")
	register_cvar("zp_knockback_nemesis", "0.25")
	register_cvar("zp_knockback_power", "1")
	register_cvar("zp_knockback_zvel", "0")
	register_cvar("zp_leap_nemesis", "1")
	register_cvar("zp_leap_nemesis_cooldown", "5.0")
	register_cvar("zp_leap_nemesis_force", "500")
	register_cvar("zp_leap_nemesis_height", "300")
	register_cvar("zp_leap_survivor", "0")
	register_cvar("zp_leap_survivor_cooldown", "5.0")
	register_cvar("zp_leap_survivor_force", "500")
	register_cvar("zp_leap_survivor_height", "300")
	register_cvar("zp_leap_zombies", "0")
	register_cvar("zp_leap_zombies_cooldown", "5.0")
	register_cvar("zp_leap_zombies_force", "500")
	register_cvar("zp_leap_zombies_height", "300")
	register_cvar("zp_lighting", "a")
	register_cvar("zp_logcommands", "1")
	register_cvar("zp_multi_chance", "20")
	register_cvar("zp_multi_enabled", "1")
	register_cvar("zp_multi_min_players", "0")
	register_cvar("zp_multi_ratio", "0.15")
	register_cvar("zp_nem_allow_respawn", "0")
	register_cvar("zp_nem_aura", "1")
	register_cvar("zp_nem_base_health", "0")
	register_cvar("zp_nem_chance", "20")
	register_cvar("zp_nem_damage", "250")
	register_cvar("zp_nem_enabled", "1")
	register_cvar("zp_nem_glow", "1")
	register_cvar("zp_nem_gravity", "0.5")
	register_cvar("zp_nem_health", "0")
	register_cvar("zp_nem_ignore_frags", "1")
	register_cvar("zp_nem_ignore_rewards", "1")
	register_cvar("zp_nem_min_players", "0")
	register_cvar("zp_nem_painfree", "0")
	register_cvar("zp_nem_speed", "250")
	register_cvar("zp_nvg_custom", "1")
	register_cvar("zp_nvg_give", "1")
	register_cvar("zp_nvg_size", "80")
	register_cvar("zp_on", "1")
	register_cvar("zp_plague_allow_respawn", "0")
	register_cvar("zp_plague_chance", "30")
	register_cvar("zp_plague_enabled", "1")
	register_cvar("zp_plague_min_players", "0")
	register_cvar("zp_plague_nem_hp_multi", "0.5")
	register_cvar("zp_plague_nem_number", "1")
	register_cvar("zp_plague_ratio", "0.5")
	register_cvar("zp_plague_surv_hp_multi", "0.5")
	register_cvar("zp_plague_surv_number", "1")
	register_cvar("zp_prevent_consecutive_modes", "1")
	register_cvar("zp_random_spawn", "1")
	register_cvar("zp_random_weapons", "0")
	register_cvar("zp_remove_doors", "0")
	register_cvar("zp_remove_dropped", "0")
	register_cvar("zp_remove_money", "1")
	register_cvar("zp_respawn_after_last_human", "1")
	register_cvar("zp_respawn_humans", "1")
	register_cvar("zp_respawn_nemesis", "1")
	register_cvar("zp_respawn_on_suicide", "0")
	register_cvar("zp_respawn_on_worldspawn_kill", "1")
	register_cvar("zp_respawn_survivors", "1")
	register_cvar("zp_respawn_zombies", "1")
	register_cvar("zp_spawn_delay", "5")
	register_cvar("zp_spawn_protection", "5")
	register_cvar("zp_starting_ammo_packs", "5")
	register_cvar("zp_stats_save", "1")
	register_cvar("zp_surv_allow_respawn", "0")
	register_cvar("zp_surv_aura", "1")
	register_cvar("zp_surv_base_health", "0")
	register_cvar("zp_surv_chance", "20")
	register_cvar("zp_surv_enabled", "1")
	register_cvar("zp_surv_glow", "1")
	register_cvar("zp_surv_gravity", "1.25")
	register_cvar("zp_surv_health", "0")
	register_cvar("zp_surv_ignore_frags", "1")
	register_cvar("zp_surv_ignore_rewards", "1")
	register_cvar("zp_surv_min_players", "0")
	register_cvar("zp_surv_painfree", "1")
	register_cvar("zp_surv_speed", "230")
	register_cvar("zp_surv_unlimited_ammo", "2")
	register_cvar("zp_surv_weapon", "weapon_m249")
	register_cvar("zp_swarm_allow_respawn", "0")
	register_cvar("zp_swarm_chance", "20")
	register_cvar("zp_swarm_enabled", "1")
	register_cvar("zp_swarm_min_players", "0")
	register_cvar("zp_thunderclap", "90")
	register_cvar("zp_triggered_lights", "1")
	register_cvar("zp_zombie_armor", "0.75")
	register_cvar("zp_zombie_bleeding", "1")
	register_cvar("zp_zombie_classes", "1")
	register_cvar("zp_zombie_damage_reward", "0")
	register_cvar("zp_zombie_first_hp", "2.0")
	register_cvar("zp_zombie_fov", "110")
	register_cvar("zp_zombie_frags_for_infect", "1")
	register_cvar("zp_zombie_hitzones", "0")
	register_cvar("zp_zombie_infect_health", "100")
	register_cvar("zp_zombie_infect_reward", "1")
	register_cvar("zp_zombie_painfree", "2")
	register_cvar("zp_zombie_silent", "1")
}
